backend:
  name: github
  branch: main
  repo: thekilnshed
  base_url: __OAUTH_WORKER_URL__
  auth_endpoint: auth

publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: pages
    label: "Pages"
    folder: "src/_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
