backend:
  name: github
  branch: main
  repo: thekilnshed
  base_url: __OAUTH_WORKER_URL__
  auth_endpoint: auth

publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: pages
    label: "Pages"
    folder: "src/_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: faqs
    label: "Faqs"
    folder: "src/_data/faqs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "string" }
      - { label: "Button Text", name: "button_text", widget: "string" }
      - { label: "Button Link", name: "link", widget: "string" }

  - name: staff
    label: "Staff"
    folder: "src/_data/staff"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Instagram Link", name: "instrgram", widget: "string" }
      - { label: "Website Link", name: "website", widget: "string" }
      - { label: "Bio", name: "bio", widget: "string" }
